### ISSUE TITLE
SQM reading

### ISSUE THREAD

**Issue by porkyhttp** [beckrd/DIY_SQM#1]
Hi,
I want to know if the SQM reading done by this device has been calibrated against an official SQM device.

In the code is reported the formula for the SQM read in mag/arcsec2
mpsas = 12.6 - 1.086 * log(VIS) + _calibrationOffset;
Where this info came from???

**Comment by beckrd** [comment]
The calibration line is directly from gshau's code.  I don't have access to an SQM device and cannot comment on the comparison between the two.  I have taken readings which correspond well to the estimated sky quality from clearoutside.com (https://clearoutside.com/forecast/29.74/-95.82).
